version: "3.7"

services:
  &db-service test-mysql: #we need to use not a ALIAS we need to use service name to connect to db
    container_name: *db-service
    hostname: *db-service
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASS password
    networks:
      - web
  &php74-fpm test-php-fpm:
    container_name: *php74-fpm
    hostname: *php74-fpm
    command: php-fpm
    environment:
      FPM_PORT: &PHP74_PORT 9000
      FPM_USER: "${CURRENT_USER_ID}"
      FPM_GROUP: "${CURRENT_USER_ID}"
      CURRENT_USER: "${CURRENT_USER}"
      SCHEDULE_PERIOD: 60
    restart: always
    build:
      ./docker/php
    volumes:
      - ./code:/var/www/html/:rw
    networks:
      - web
  &httpd test-httpd:
    container_name: *httpd
    hostname: *httpd
    environment:
      PHP74_HOST: *php74-fpm
      PHP74_PORT: *PHP74_PORT
    volumes:
      - ./code:/var/www/html/
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    build:
      ./docker/apache
    ports:
      - ${APACHE_CONTAINER_PORT}:80
    restart: always
    networks:
      - web
    depends_on:
      - *db-service
  #  &db-service test-mysql:
  #    container_name: *db-service
  #    hostname: *db-service
  #    image: mysql:5.6
  #    volumes:
  #      - db:/var/lib/mysql
  #    environment:
  #      MYSQL_DATABASE: exampledb
  #      MYSQL_ROOT_PASSWORD: password


  &pma-service test-phpmyadmin:
    container_name: *pma-service
    hostname: *pma-service
    image: phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: *db-service
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8081:80
    networks:
      - web
    depends_on:
      - *db-service

  &node-service test-node:
    container_name: *node-service
    hostname: *node-service
    restart: on-failure
    user: "1000:1000"
    image: node:latest
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html/:rw

volumes:
  db:
networks:
  web:
